name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.teste }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@93.127.210.249 'cd /var/www/clients/client0/web1/web && git pull origin main'
